#!/bin/sh

echo "Setting keyboard shit to default."

defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool true
defaults delete NSGlobalDomain KeyRepeat
defaults delete NSGlobalDomain InitialKeyRepeat

echo "Quit Terminal and relaunch a new sesh."
