#!/bin/sh
hidutil property --set '{"UserKeyMapping":
    [{"HIDKeyboardModifierMappingSrc":0x700000039,
      "HIDKeyboardModifierMappingDst":0x700000029},
     {"HIDKeyboardModifierMappingSrc":0x700000029,
      "HIDKeyboardModifierMappingDst":0x700000039},
     {"HIDKeyboardModifierMappingSrc":0x7000000E2,
      "HIDKeyboardModifierMappingDst":0x7000000E1},
     {"HIDKeyboardModifierMappingSrc":0x7000000E6,
      "HIDKeyboardModifierMappingDst":0x7000000E5},
     {"HIDKeyboardModifierMappingSrc":0x7000000E0,
      "HIDKeyboardModifierMappingDst":0x7000000E2},
     {"HIDKeyboardModifierMappingSrc":0x7000000E1,
      "HIDKeyboardModifierMappingDst":0x7000000E0},
     {"HIDKeyboardModifierMappingSrc":0x7000000E5,
      "HIDKeyboardModifierMappingDst":0x7000000E0}]
}'
